import { Header } from "@components/Header";
import { PreviewSection } from "@components/PreviewSection";
import { ProjectSection } from "@components/ProjectSection";
import { CooperationSection } from "@components/CooperationSection";
import Head from "next/head"
import { Footer } from "@components/Footer";

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <PreviewSection />
        <ProjectSection />
        <CooperationSection />
      </main>

      <Footer />
    </>
  );
}
